### ISSUE TITLE
Add a .Net Core DistributedCache

### ISSUE THREAD

**Issue by hazzik** [nhibernate/NHibernate-Caches#28]
Add a [distributed cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed) implementation.

**Comment by fredericDelaporte** [comment]
Yes, that was my intend, after having finished with the memory one. I have yet to investigate it, but I hope this could be done as a generic distributed cache, accepting any provider, likely through a setting.

**Comment by fredericDelaporte** [comment]
Well, due to this caching system relying solely on `Microsoft.Extensions.DependencyInjection` for bootstrapping and supplying settings to it, I do not see any solution for handling many different providers than requiring a factory from consumer...

Each `IDistributedCache` implementation constructor takes its own option class. It does not look any mechanism exists for instanciating an `IDistributedCache` implementation solely from its class name. (There is no default constructor which would seek its option in hosting application configuration.)
