### ISSUE TITLE
NullReferenceException in SysCache2's SysCacheProvider

### ISSUE THREAD

**Issue by pascallaprade** [nhibernate/NHibernate-Caches#40]
In commit https://github.com/nhibernate/NHibernate-Caches/commit/d7e1dc9316919087ed4b3494e1a23bb1ad5384a4#diff-fdf851d99f0719e7ffb772921c9f01ef, a line was removed (`CacheRegions = new Dictionary<string, SysCacheRegion>(0);`) which now causes a `NullReferenceException` with our configuration.

We mark each entity as cacheable, in our mappings, but we do not define any region manually in our web.config file.

As such, because our `configSection.CacheRegions.Count` is always 0, `CacheRegionSettings` ends up being never initialized, and we get a `NullReferenceException`.

You should not attempt to reference an uninitialized property, to avoid such exceptions being thrown at runtime.

If it is intended for this use case not to work, you should manually throw an exception describing the problem, instead of relying on a nondescriptive `NullReferenceException`.

I will provide a pull request to avoid the exception soon.

**Comment by fredericDelaporte** [comment]
The removal of that line is not the cause of the null reference exception. `CacheRegions` is still always initialized by the way, since it is now done at its declaration. That is why the line has been removed. You are mixing up `CacheRegions` with `CacheRegionSettings`, which can be null when there are no regions, which is a bug. Putting back `CacheRegions = new Dictionary<string, SysCacheRegion>(0);` would not change anything, since that dictionary would still be empty, so `CacheRegionSettings` will still remain uninitialized.

In fact, that is a `CacheRegionSettings = new Dictionary<string, CacheRegionElement>(0);` line which is missing in that place. This case has just been overlooked.

**Comment by fredericDelaporte** [comment]
A 5.3.2 version of SysCache2 fixing this trouble is now published. Thanks for the report.
https://github.com/nhibernate/NHibernate-Caches/releases/tag/5.3.2
