### ISSUE TITLE
StackExchangeRedis fails with "too many results to unpack" with 8000 items

### ISSUE THREAD

**Issue by panuva-sympa** [nhibernate/NHibernate-Caches#62]
StackExchangeRedis fails with "too many results to unpack" when querying with SetCacheable() under certain circumstances.

This happens (only) when the following occur at same time:
- using FastRegionStrategy
- with Sliding expiration
- the collection is big >8000 items I assume.

The call we make is something like:
```C#
session.Query<MyClass>().
  WithOptions(o => o.SetCacheable(true)).
  Where(x => x.Zz.Id == theId).ToListAsync();
```

Exception looks like:
```
DefaultSocketManager:Completion:2|NHibernate.Util.ADOExceptionReporter|ERR Error running script (call to f_f9ee676fc28fa27545ce0818084....):
 @user_script:2: user_script:2: too many results to unpack 
``` 

Using NHibernate.Caches.StackExchangeRedis v 5.5.1. Pinpointed the issue to
https://github.com/nhibernate/NHibernate-Caches/blob/790b3841daf12859a2635d82dd96840168fff85b/StackExchangeRedis/NHibernate.Caches.StackExchangeRedis/Lua/FastRegionStrategy/SlidingGetMany.lua#L2

Quoting from random web resource, many referring to the same 8000 default limit for unpack: "That said, unpack() actually has a limit on the size of the table which is defined by LUAI_MAXCSTACK in luaconf.h forcing a maximum number of Lua stack slots that a C function can use. This limit is set to 8000 by default"

The question is:
1) how it could batch it so that the unpack() wouldn't fail to hitting >8000 items
2) could it be easily worked around somehow else with the current issue existing

**Comment by panuva-sympa** [comment]
This seems to be related (doing splitting to batches, for another call):
https://github.com/antirez/redis/issues/678#issuecomment-15848571

Not looking too "clean", but perhaps a way to implement batching when needed. 

Elaboration: it is not trivial what would be the desired batch size (this issue comment referring to 1024 stack size, some others give the 8000) -- likely some configurable value could be best/most flexible, with default set to the common values used for building redis.

**Comment by maca88** [comment]
> how it could batch it so that the unpack() wouldn't fail to hitting >8000 items

Until this is fixed you can create a custom strategy that extends `FastRegionStrategy` and override the `GetManyScript` where you can put a custom lua script that splits in batches or by using `get` for each key.

I will analyze few different approaches to solve the problem (split to multiple `mget` calls or by using `get`) and will implement the fastest one.

**Comment by maca88** [comment]
The default limit of arguments for a function is 8000 (tested). After some testing I've found out that calling `mget` in a lua script does not give any performance benefits in comparison to `get`.

Script that uses `mget` to retrieve the values:
```
local expirationMs = ARGV[2]
local step = ARGV[3]
local values = {}
local i = 0
while i < #KEYS do
	local result = redis.call('mget', unpack(KEYS, i + 1, math.min(i + step, #KEYS)))
	for j=1,#result do
		values[i + j] = result[j]
		if result[j] ~= nil then
			redis.call('pexpire', KEYS[i + j], expirationMs)
		end
	end
	i = i + step
end
return values
```

***MGET splitting by 10 keys (step = 10)***
Batch size: 10000
Times per iteration 442ms,446ms,379ms,392ms,434ms
Average 418,6ms

***MGET splitting by 1000 keys (step = 1000)***
Batch size: 10000
Times per iteration 495ms,403ms,431ms,462ms,372ms
Average 432,6ms

***MGET splitting by 5000 keys (step = 5000)***
Batch size: 10000
Times per iteration 446ms,453ms,390ms,420ms,472ms
Average 436,2ms


Script that uses `get` to retrieve the values
```
local expirationMs = ARGV[2]
local values = {}
for i=1,#KEYS do
	values[i] = redis.call('get', KEYS[i])
	if values[i] ~= nil then
		redis.call('pexpire', KEYS[i], expirationMs)
	end
end
return values
```

***GET for each key***
Batch size: 10000
Times per iteration 441ms,422ms,364ms,377ms,430ms
Average 406,8ms

As it can be seen from the benchmarks, `get` is the fastest option and also the simplest to implement as it does not require an additional setting. I've made a PR which uses `get` instead of `mget`

**Comment by fredericDelaporte** [comment]
Have you done this benchmark with a Redis server not running locally? Or is the script anyway running directly on the server, avoiding multiples IO when switching from `mget` to `get`?

**Comment by maca88** [comment]
The benchmarks are done with a local Redis server in order to avoid having network latencies in the final result. Lua scripts are send to the Redis server where they are executed, so using `get` or `mget` inside the script does not produce any I/O operation, at least not between the application and Redis server.
