### ISSUE TITLE
Cache issue-.net core 3.0-Could not load type 'System.Web.Caching.CacheItemPriority' 

### ISSUE THREAD

**Issue by nambir** [nhibernate/NHibernate-Caches#77]
I was using nhibernate for Cache in old .net framework.

Now we are rewriting to .net core 3.0.

We are having runtime issue for nhibernate cache. 

**Inner Exception**
Could not load type 'System.Web.Caching.CacheItemPriority' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.":"System.Web.Caching.CacheItemPriority

**Exception:**
{"An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.\r\n\r\n

![nhibernate cache issue](https://user-images.githubusercontent.com/16057911/71085616-f0c1f500-21bd-11ea-9831-35b598e4d59b.jpg)

**Comment by maca88** [comment]
`NHibernate.Caches.SysCache2` does not support .NET Core, because `System.Web.Caching` was not ported. You will have to switch to one of the following caches:
- `NHibernate.Caches.CoreMemoryCache`
- `NHibernate.Caches.CoreDistributedCache.Memcached`
- `NHibernate.Caches.CoreDistributedCache.Redis`
- `NHibernate.Caches.CoreDistributedCache.SqlServer`
- `NHibernate.Caches.StackExchangeRedis`
- `NHibernate.Caches.RtMemoryCache`

The closest to `SysCache2` cache is `NHibernate.Caches.CoreDistributedCache.SqlServer`, you can try to use it instead.

**Comment by nambir** [comment]
Hi Could you have any link which has the sample code for implementing 1.'NHibernate.Caches.CoreDistributedCache.SqlServer"
2.NHibernate.Caches.CoreMemoryCache

**Comment by maca88** [comment]
You can check how the tests are configured:
1. [SqlServer](https://github.com/nhibernate/NHibernate-Caches/blob/master/CoreDistributedCache/NHibernate.Caches.CoreDistributedCache.Tests/App.config#L50)
2. [CoreMemoryCache](https://github.com/nhibernate/NHibernate-Caches/blob/master/CoreMemoryCache/NHibernate.Caches.CoreMemoryCache.Tests/App.config#L9)

**Comment by fredericDelaporte** [comment]
I have frequently seen people using `SysCache2` instead of `SysCache`, believing `SysCache2` was a later version of it. It is not the case. Granted, the naming is misleading. `SysCache2` is `SysCache` with Sql Server dependencies, allowing it to be invalidated by events occurring on db-side. If you are not using this feature, you can use any equivalent of `SysCache`, which is a memory based cache.

See the [documentation](https://nhibernate.info/doc/nhibernate-reference/caches.html).

It lags a bit, `RtMemoryCache` is now available for .Net Core too despite what is written in the documentation. And for a pure memory cache, `RtMemoryCache` would be my personal choice.

**Comment by Stumblor** [comment]
@fredericDelaporte we are using syscache2 for the sql cache dependency functionality, as we have multiple apps interacting with the same database that need to inform each other of changes. 

Do any of the new .netcore caching options support this feature?

**Comment by fredericDelaporte** [comment]
Currently, no. I do not believe the underlying .Net Framework functionalities required for sysache2 have been ported to .Net Core.

If they are available in .Net Core, you may PR an update to SysCache2 for supporting .Net Core, if doable through an update. Otherwise if it is available in .Net Core but through something too different for an update, you may contribute a new cache provider (preferably better named).

**Comment by fredericDelaporte** [comment]
Searching a bit the subject again, it seems syscache2 required dependency will not be ported to .Net Core, so syscache2 will remain a .Net Framework only library.

But some other functionalities like [`SqlDependency`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldependency) (available as a Platform extension) may allow to create a new provider similar tos yscache2, perhaps named `SqlDependencyCache` by example. It would have to replace the `System.Web.Caching` by a pure memory cache like `System.Runtime.Caching` then use `SqlDependency` to handle the SQL Server dependencies.
